import { LegalLayout } from "../legal-layout";

export default function TermsPage() {
  return <LegalLayout title="Nutzungsbedingungen">
    <section><h2>1. Anbieter und Geltungsbereich</h2><p>Diese Bedingungen gelten für THE.HUMAN.CHOICE und Road to 100 Push-ups. Anbieter ist Roman Dossenbach, Steinackerstrasse 16, 79576 Weil am Rhein, Deutschland, E-Mail: <a href="mailto:pushupmania@gmail.com">pushupmania@gmail.com</a>. Mit der Registrierung stimmt der Nutzer diesen Bedingungen zu.</p></section>
    <section><h2>2. Zweck der Apps</h2><p>Die Apps dienen der Erfassung von Liegestützen, der Dokumentation des Trainingsfortschritts, der Teilnahme an Herausforderungen und dem freiwilligen Vergleich mit anderen Athleten. Trainingshinweise ersetzen keine ärztliche, physiotherapeutische oder sportmedizinische Beratung.</p></section>
    <section><h2>3. Gemeinsames Benutzerkonto</h2><p>Beide Apps verwenden dasselbe Benutzerkonto. Dieselbe E-Mail-Adresse darf nicht zu einem zweiten Athletenprofil führen. Trainingseinträge und erreichte Liegestütze werden automatisch zwischen beiden Apps synchronisiert und dem gemeinsamen Profil zugeordnet. Eine zusätzliche Bestätigung jedes einzelnen Eintrags ist nicht erforderlich. Zugangsdaten dürfen nicht an andere Personen weitergegeben werden.</p></section>
    <section><h2>4. Registrierung und öffentliche Rangliste</h2><p>Angaben müssen vollständig und wahrheitsgemäß sein. In der öffentlichen Rangliste können Vorname, abgekürzter Nachname, Alter oder Altersklasse, Land, Geschlecht beziehungsweise Ranglistenkategorie, freiwilliges Profilfoto sowie Trainings-, Durchschnitts- und Ranglistenwerte erscheinen. E-Mail-Adresse, Passwort, Anschrift und vollständiges Geburtsdatum werden nicht öffentlich angezeigt.</p></section>
    <section><h2>5. Ehrlichkeit und faire Nutzung</h2><p>Leistungen sind ehrlich und nach bestem Wissen einzutragen. Verboten sind erfundene Einträge, technische Manipulationen, Mehrfachkonten zur Beeinflussung der Rangliste, Einträge für andere Personen ohne Zustimmung sowie automatisierte Angriffe. Offensichtlich falsche Ergebnisse können korrigiert oder gelöscht werden. Bei schweren oder wiederholten Verstößen kann das Konto gesperrt oder gelöscht werden.</p></section>
    <section><h2>6. Gesundheit und Eigenverantwortung</h2><p>Das Training erfolgt freiwillig und auf eigene Verantwortung. Bei Schmerzen, Schwindel, Atemnot, ungewöhnlichem Unwohlsein oder Verletzungszeichen ist es sofort abzubrechen. Bei Erkrankungen, Beschwerden oder Unsicherheit ist vor Trainingsbeginn ärztlicher Rat einzuholen. Ein bestimmter Trainingserfolg oder Weltrekord wird nicht versprochen.</p></section>
    <section><h2>7. Community-Regeln</h2><p>Nutzer müssen andere respektvoll behandeln. Beleidigende, diskriminierende, bedrohende oder rechtswidrige Inhalte, Belästigungen, Spam sowie die Veröffentlichung fremder personenbezogener Daten sind untersagt und können entfernt werden.</p></section>
    <section><h2>8. Schutz vor Kopieren</h2><p>Apps, Trainingskonzepte, Texte, Anleitungen, Bilder, Videos, Grafiken, Logos, Bezeichnungen, Ranglistenaufbereitung, Datenbankstrukturen, Software und Erscheinungsbild sind geschützt, soweit die gesetzlichen Voraussetzungen erfüllt sind.</p><p>Ohne vorherige schriftliche Genehmigung von Roman Dossenbach ist es insbesondere nicht gestattet, wesentliche Inhalte oder Gestaltungselemente zu kopieren, Trainingsprogramme zu übernehmen oder weiterzuverkaufen, Daten oder Ranglisten automatisiert auszulesen, Namen oder Logos für eigene Angebote zu verwenden oder eine identische beziehungsweise irreführend ähnliche App auf Grundlage geschützter Inhalte zu erstellen. Zwingende gesetzliche Nutzungsrechte bleiben unberührt.</p></section>
    <section><h2>9. Inhalte der Nutzer</h2><p>Nutzer behalten ihre Rechte an eigenen Inhalten. Sie räumen dem Anbieter die für Kontoführung, Profildarstellung, Rangliste, Speicherung und App-Funktionen erforderlichen, nicht ausschließlichen Nutzungsrechte ein. Hochgeladene Fotos und Videos dürfen nur verwendet werden, wenn der Nutzer die erforderlichen Rechte besitzt.</p></section>
    <section><h2>10. Verfügbarkeit und Haftung</h2><p>Eine jederzeitige, unterbrechungsfreie oder fehlerfreie Verfügbarkeit wird nicht garantiert. Der Anbieter haftet unbeschränkt bei Vorsatz, grober Fahrlässigkeit sowie bei schuldhafter Verletzung von Leben, Körper oder Gesundheit. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den typischerweise vorhersehbaren Schaden begrenzt. Zwingende gesetzliche Ansprüche bleiben unberührt.</p></section>
    <section><h2>11. Kontolöschung</h2><p>Das gemeinsame Konto kann in den persönlichen Daten über „Konto löschen“ oder per E-Mail gelöscht werden. Die Löschung betrifft beide Apps und die zugeordneten Trainingseinträge, soweit keine gesetzlichen Aufbewahrungspflichten bestehen.</p></section>
    <section><h2>12. Minderjährige</h2><p>Die selbstständige Registrierung ist grundsätzlich ab 16 Jahren gestattet. Jüngere Personen dürfen die Apps nur mit Zustimmung ihrer Erziehungsberechtigten verwenden.</p></section>
    <section><h2>13. Änderungen und Recht</h2><p>Wesentliche Änderungen dieser Bedingungen werden innerhalb der App oder per E-Mail mitgeteilt. Es gilt deutsches Recht. Zwingende Verbraucherschutzvorschriften am gewöhnlichen Aufenthaltsort des Nutzers bleiben unberührt.</p></section>
  </LegalLayout>;
}
