"use client";

import { useEffect, useState } from "react";
import { extraWords } from "./i18n-extra";

export type Language = "de" | "en" | "fr" | "es" | "it" | "pt" | "bg" | "tr" | "hu" | "ar";
export const languages: { code: Language; label: string }[] = [
  { code: "de", label: "Deutsch" }, { code: "en", label: "English" },
  { code: "fr", label: "Français" }, { code: "es", label: "Español" },
  { code: "it", label: "Italiano" }, { code: "pt", label: "Português" },
  { code: "bg", label: "Български" }, { code: "tr", label: "Türkçe" },
  { code: "hu", label: "Magyar" },
  { code: "ar", label: "العربية" },
];

const words = {
  de: {
    statistics:"Statistik", worldRecords:"Worldrecords", motivation:"Motivation", roadTo100:"Road to 100 Push-ups", yourChoice:"Push-up Challenge",
    lastName:"Nachname", yourLastName:"Dein Nachname", backApp:"Zurück zur App", communityRanking:"Community-Rangliste", allAthletes:"Alle Athleten", rankingMotivation:"Sieh, was die Community erreicht hat, und lass dich für dein nächstes Training motivieren.", rank:"Rang", athlete:"Athlet", monthlyAverage:"Monatsschnitt",
    athleteProfile:"Athletenprofil", profileNeeded:"Vor dem ersten Speichern ergänzen",
    menRanking:"Öffentliche Rangliste für Männer", every:"Jeder Push-up zählt.", intro:"Trage die Anzahl deiner technisch korrekt ausgeführten Push-ups ein.", firstName:"Vorname des Athleten", yourName:"Dein Vorname", country:"Land", countryExample:"z. B. Schweiz", birthDate:"Geburtsdatum", optional:"freiwillig", profileHelp:"Pflichtfelder: Vorname und Land. Das Geburtsdatum ist freiwillig und wird nur zur Anzeige des Alters verwendet.", tap:"ZUM ZÄHLEN TIPPEN", writeCount:"Anzahl schreiben", add:"Hinzufügen", videoProof:"Optionaler Video-Nachweis", chooseVideo:"Video wählen", save:"Training speichern", saving:"Wird gespeichert …", signInHint:"Zum Speichern und Verwalten deiner Trainings bitte mit E-Mail und Passwort anmelden.", total:"Gesamt", thisMonth:"Diesen Monat", athletes:"Athleten", worldwide:"weltweit", trainingLog:"Dein Trainingsbuch", recent:"Deine letzten Einträge.", currentMonth:"Aktueller Monat", monthRanking:"Monatsrangliste.", allWorkouts:"Alle Trainings", totalRanking:"Gesamtrangliste.", newcomer:"Faire Wertung für Neueinsteiger", forecast:"30-Tage-Prognose.", forecastNote:"Der Durchschnitt pro aktivem Trainingstag wird auf 30 Tage hochgerechnet. Beispiel: 30 täglich ergeben 900 Push-ups.", rankAthlete:"Rang · Athlet", month:"Monat", avgDay:"Ø / Tag", activeDays:"Aktive Tage", days30:"30 Tage", rules:"Regeln & Ehrlichkeit", creatorLine:"Die Community zählt auf Ehrlichkeit.", login:"Anmelden / Konto erstellen", signedIn:"Angemeldet als", logout:"Abmelden", videoFormat:"MP4, WebM oder MOV · maximal 30 MB", noMonth:"Noch keine Einträge in diesem Monat.", noTotal:"Noch keine Einträge in der Gesamtrangliste.", noForecast:"Sobald ein Training gespeichert wurde, erscheint hier die erste Prognose.", loading:"Wird geladen …"
  },
  en: {
    statistics:"Statistics", worldRecords:"World records", motivation:"Motivation", roadTo100:"Road to 100 Push-ups", yourChoice:"Push-up Challenge",
    lastName:"Last name", yourLastName:"Your last name", backApp:"Back to app", communityRanking:"Community ranking", allAthletes:"All athletes", rankingMotivation:"See what the community has achieved and get motivated for your next workout.", rank:"Rank", athlete:"Athlete", monthlyAverage:"Monthly average",
    athleteProfile:"Athlete profile", profileNeeded:"Complete before your first save",
    menRanking:"Public ranking for men", every:"Every push-up counts.", intro:"Tap the area for each repetition or enter the number of a completed set.", firstName:"Athlete's first name", yourName:"Your first name", country:"Country", countryExample:"e.g. Switzerland", birthDate:"Date of birth", optional:"optional", profileHelp:"Required: first name and country. Date of birth is optional and is only used to display age.", tap:"TAP TO COUNT", writeCount:"Enter number", add:"Add", videoProof:"Optional video evidence", chooseVideo:"Choose video", save:"Save workout", saving:"Saving …", signInHint:"To save and manage your workouts, please sign in with email and password.", total:"Total", thisMonth:"This month", athletes:"Athletes", worldwide:"worldwide", trainingLog:"Your training log", recent:"Your latest entries.", currentMonth:"Current month", monthRanking:"Monthly ranking.", allWorkouts:"All workouts", totalRanking:"Overall ranking.", newcomer:"Fair ranking for newcomers", forecast:"30-day forecast.", forecastNote:"The average per active training day is projected over 30 days. Example: 30 per day equals 900 push-ups.", rankAthlete:"Rank · Athlete", month:"Month", avgDay:"Avg / day", activeDays:"Active days", days30:"30 days", rules:"Rules & honesty", creatorLine:"The community counts on honesty.", login:"Sign in / Create account", signedIn:"Signed in as", logout:"Sign out", videoFormat:"MP4, WebM or MOV · maximum 30 MB", noMonth:"No entries this month yet.", noTotal:"No entries in the overall ranking yet.", noForecast:"Your first forecast will appear after you save a workout.", loading:"Loading …"
  },
  fr: {
    statistics:"Statistiques", worldRecords:"Records du monde", motivation:"Motivation", roadTo100:"Objectif 100 pompes", yourChoice:"Push-up Challenge",
    lastName:"Nom", yourLastName:"Votre nom", backApp:"Retour à l’app", communityRanking:"Classement communauté", allAthletes:"Tous les athlètes", rankingMotivation:"Découvrez les résultats de la communauté et motivez-vous pour votre prochain entraînement.", rank:"Rang", athlete:"Athlète", monthlyAverage:"Moyenne mensuelle",
    athleteProfile:"Profil de l’athlète", profileNeeded:"À compléter avant le premier enregistrement",
    menRanking:"Classement public hommes", every:"Chaque pompe compte.", intro:"Touchez la zone pour chaque répétition ou saisissez le nombre d'une série terminée.", firstName:"Prénom de l'athlète", yourName:"Votre prénom", country:"Pays", countryExample:"p. ex. Suisse", birthDate:"Date de naissance", optional:"facultatif", profileHelp:"Obligatoire : prénom et pays. La date de naissance est facultative et sert uniquement à afficher l'âge.", tap:"TOUCHER POUR COMPTER", writeCount:"Saisir le nombre", add:"Ajouter", videoProof:"Preuve vidéo facultative", chooseVideo:"Choisir une vidéo", save:"Enregistrer l'entraînement", saving:"Enregistrement …", signInHint:"Pour enregistrer et gérer vos entraînements, connectez-vous avec votre e-mail et votre mot de passe.", total:"Total", thisMonth:"Ce mois-ci", athletes:"Athlètes", worldwide:"monde entier", trainingLog:"Votre carnet d'entraînement", recent:"Vos dernières entrées.", currentMonth:"Mois en cours", monthRanking:"Classement mensuel.", allWorkouts:"Tous les entraînements", totalRanking:"Classement général.", newcomer:"Classement équitable pour débutants", forecast:"Prévision sur 30 jours.", forecastNote:"La moyenne par jour d'entraînement actif est projetée sur 30 jours. Exemple : 30 par jour donnent 900 pompes.", rankAthlete:"Rang · Athlète", month:"Mois", avgDay:"Moy. / jour", activeDays:"Jours actifs", days30:"30 jours", rules:"Règles et honnêteté", creatorLine:"La communauté compte sur l'honnêteté.", login:"Connexion / Créer un compte", signedIn:"Connecté en tant que", logout:"Déconnexion", videoFormat:"MP4, WebM ou MOV · maximum 30 Mo", noMonth:"Aucune entrée ce mois-ci.", noTotal:"Aucune entrée au classement général.", noForecast:"La première prévision apparaîtra après un entraînement enregistré.", loading:"Chargement …"
  },
  es: {
    statistics:"Estadísticas", worldRecords:"Récords mundiales", motivation:"Motivación", roadTo100:"Camino a 100 flexiones", yourChoice:"Push-up Challenge",
    lastName:"Apellido", yourLastName:"Tu apellido", backApp:"Volver a la app", communityRanking:"Ranking de la comunidad", allAthletes:"Todos los atletas", rankingMotivation:"Mira lo que ha logrado la comunidad y motívate para tu próximo entrenamiento.", rank:"Puesto", athlete:"Atleta", monthlyAverage:"Promedio mensual",
    athleteProfile:"Perfil del atleta", profileNeeded:"Completar antes de guardar por primera vez",
    menRanking:"Clasificación pública masculina", every:"Cada flexión cuenta.", intro:"Toca el área por cada repetición o introduce el número de una serie terminada.", firstName:"Nombre del atleta", yourName:"Tu nombre", country:"País", countryExample:"p. ej. España", birthDate:"Fecha de nacimiento", optional:"opcional", profileHelp:"Obligatorio: nombre y país. La fecha de nacimiento es opcional y solo se usa para mostrar la edad.", tap:"TOCA PARA CONTAR", writeCount:"Introducir cantidad", add:"Añadir", videoProof:"Prueba de vídeo opcional", chooseVideo:"Elegir vídeo", save:"Guardar entrenamiento", saving:"Guardando …", signInHint:"Para guardar y gestionar tus entrenamientos, inicia sesión con correo y contraseña.", total:"Total", thisMonth:"Este mes", athletes:"Atletas", worldwide:"en todo el mundo", trainingLog:"Tu diario de entrenamiento", recent:"Tus últimas entradas.", currentMonth:"Mes actual", monthRanking:"Clasificación mensual.", allWorkouts:"Todos los entrenamientos", totalRanking:"Clasificación general.", newcomer:"Clasificación justa para principiantes", forecast:"Proyección de 30 días.", forecastNote:"El promedio por día de entrenamiento activo se proyecta a 30 días. Ejemplo: 30 al día son 900 flexiones.", rankAthlete:"Puesto · Atleta", month:"Mes", avgDay:"Prom. / día", activeDays:"Días activos", days30:"30 días", rules:"Reglas y honestidad", creatorLine:"La comunidad confía en la honestidad.", login:"Entrar / Crear cuenta", signedIn:"Sesión iniciada como", logout:"Cerrar sesión", videoFormat:"MP4, WebM o MOV · máximo 30 MB", noMonth:"Aún no hay entradas este mes.", noTotal:"Aún no hay entradas en la clasificación general.", noForecast:"La primera proyección aparecerá al guardar un entrenamiento.", loading:"Cargando …"
  },
  it: {
    statistics:"Statistiche", worldRecords:"Record mondiali", motivation:"Motivazione", roadTo100:"Verso 100 push-up", yourChoice:"Push-up Challenge",
    lastName:"Cognome", yourLastName:"Il tuo cognome", backApp:"Torna all’app", communityRanking:"Classifica community", allAthletes:"Tutti gli atleti", rankingMotivation:"Scopri i risultati della community e trova motivazione per il prossimo allenamento.", rank:"Posizione", athlete:"Atleta", monthlyAverage:"Media mensile",
    athleteProfile:"Profilo dell’atleta", profileNeeded:"Completa prima del primo salvataggio",
    menRanking:"Classifica pubblica maschile", every:"Ogni push-up conta.", intro:"Tocca l'area per ogni ripetizione o inserisci il numero di una serie completata.", firstName:"Nome dell'atleta", yourName:"Il tuo nome", country:"Paese", countryExample:"es. Svizzera", birthDate:"Data di nascita", optional:"facoltativa", profileHelp:"Obbligatori: nome e paese. La data di nascita è facoltativa e serve solo per mostrare l'età.", tap:"TOCCA PER CONTARE", writeCount:"Inserisci numero", add:"Aggiungi", videoProof:"Prova video facoltativa", chooseVideo:"Scegli video", save:"Salva allenamento", saving:"Salvataggio …", signInHint:"Per salvare e gestire gli allenamenti, accedi con e-mail e password.", total:"Totale", thisMonth:"Questo mese", athletes:"Atleti", worldwide:"nel mondo", trainingLog:"Il tuo diario di allenamento", recent:"Le tue ultime registrazioni.", currentMonth:"Mese corrente", monthRanking:"Classifica mensile.", allWorkouts:"Tutti gli allenamenti", totalRanking:"Classifica generale.", newcomer:"Classifica equa per principianti", forecast:"Proiezione a 30 giorni.", forecastNote:"La media per giorno di allenamento attivo viene proiettata su 30 giorni. Esempio: 30 al giorno equivalgono a 900 push-up.", rankAthlete:"Pos. · Atleta", month:"Mese", avgDay:"Media / giorno", activeDays:"Giorni attivi", days30:"30 giorni", rules:"Regole e onestà", creatorLine:"La comunità conta sull'onestà.", login:"Accedi / Crea account", signedIn:"Accesso come", logout:"Esci", videoFormat:"MP4, WebM o MOV · massimo 30 MB", noMonth:"Nessuna registrazione questo mese.", noTotal:"Nessuna registrazione nella classifica generale.", noForecast:"La prima proiezione apparirà dopo aver salvato un allenamento.", loading:"Caricamento …"
  },
  pt: {
    statistics:"Estatísticas", worldRecords:"Recordes mundiais", motivation:"Motivação", roadTo100:"Rumo a 100 flexões", yourChoice:"Push-up Challenge",
    lastName:"Apelido", yourLastName:"O seu apelido", backApp:"Voltar à app", communityRanking:"Ranking da comunidade", allAthletes:"Todos os atletas", rankingMotivation:"Veja o que a comunidade alcançou e motive-se para o próximo treino.", rank:"Posição", athlete:"Atleta", monthlyAverage:"Média mensal",
    athleteProfile:"Perfil do atleta", profileNeeded:"Preencher antes de guardar pela primeira vez",
    menRanking:"Ranking público masculino", every:"Cada flexão conta.", intro:"Toque na área para cada repetição ou introduza o número de uma série concluída.", firstName:"Nome do atleta", yourName:"O seu nome", country:"País", countryExample:"ex. Portugal", birthDate:"Data de nascimento", optional:"opcional", profileHelp:"Obrigatório: nome e país. A data de nascimento é opcional e serve apenas para mostrar a idade.", tap:"TOQUE PARA CONTAR", writeCount:"Introduzir número", add:"Adicionar", videoProof:"Prova em vídeo opcional", chooseVideo:"Escolher vídeo", save:"Guardar treino", saving:"A guardar …", signInHint:"Para guardar e gerir os treinos, inicie sessão com e-mail e palavra-passe.", total:"Total", thisMonth:"Este mês", athletes:"Atletas", worldwide:"em todo o mundo", trainingLog:"O seu diário de treino", recent:"Os seus últimos registos.", currentMonth:"Mês atual", monthRanking:"Ranking mensal.", allWorkouts:"Todos os treinos", totalRanking:"Ranking geral.", newcomer:"Ranking justo para iniciantes", forecast:"Projeção de 30 dias.", forecastNote:"A média por dia de treino ativo é projetada para 30 dias. Exemplo: 30 por dia equivalem a 900 flexões.", rankAthlete:"Pos. · Atleta", month:"Mês", avgDay:"Média / dia", activeDays:"Dias ativos", days30:"30 dias", rules:"Regras e honestidade", creatorLine:"A comunidade conta com a honestidade.", login:"Entrar / Criar conta", signedIn:"Sessão iniciada como", logout:"Sair", videoFormat:"MP4, WebM ou MOV · máximo 30 MB", noMonth:"Ainda não há registos este mês.", noTotal:"Ainda não há registos no ranking geral.", noForecast:"A primeira projeção aparecerá depois de guardar um treino.", loading:"A carregar …"
  }
} as Record<Language, Record<string, string>>;

words.bg = {...words.en, statistics:"Статистика", worldRecords:"Световни рекорди", motivation:"Мотивация", roadTo100:"Път към 100 лицеви опори", yourChoice:"Предизвикателство с лицеви опори", lastName:"Фамилия", yourLastName:"Вашата фамилия", backApp:"Назад към приложението", communityRanking:"Класация на общността", allAthletes:"Всички атлети", rank:"Място", athlete:"Атлет", monthlyAverage:"Средно за месеца", athleteProfile:"Профил на атлета", profileNeeded:"Попълнете преди първото запазване", menRanking:"Публична класация за мъже", every:"Всяка лицева опора се брои.", intro:"Докоснете за всяко повторение или въведете броя на завършена серия.", firstName:"Име на атлета", yourName:"Вашето име", country:"Държава", countryExample:"напр. България", birthDate:"Дата на раждане", optional:"по желание", tap:"ДОКОСНЕТЕ, ЗА ДА БРОИТЕ", writeCount:"Въведете брой", add:"Добавяне", videoProof:"Видео доказателство по желание", chooseVideo:"Избор на видео", save:"Запазване на тренировката", saving:"Запазване …", total:"Общо", thisMonth:"Този месец", athletes:"Атлети", worldwide:"по света", trainingLog:"Вашият тренировъчен дневник", recent:"Последните ви записи.", currentMonth:"Текущ месец", monthRanking:"Месечна класация.", allWorkouts:"Всички тренировки", totalRanking:"Обща класация.", rules:"Правила и честност", creatorLine:"Общността разчита на честността.", login:"Вход / Създаване на акаунт", signedIn:"Влезли сте като", logout:"Изход", loading:"Зареждане …"};
words.tr = {...words.en, statistics:"İstatistikler", worldRecords:"Dünya rekorları", motivation:"Motivasyon", roadTo100:"100 Şınava Giden Yol", yourChoice:"Şınav Mücadelesi", lastName:"Soyadı", yourLastName:"Soyadınız", backApp:"Uygulamaya dön", communityRanking:"Topluluk sıralaması", allAthletes:"Tüm sporcular", rank:"Sıra", athlete:"Sporcu", monthlyAverage:"Aylık ortalama", athleteProfile:"Sporcu profili", profileNeeded:"İlk kayıttan önce tamamlayın", menRanking:"Erkekler genel sıralaması", every:"Her şınav önemlidir.", intro:"Her tekrar için dokunun veya tamamlanan setin sayısını girin.", firstName:"Sporcunun adı", yourName:"Adınız", country:"Ülke", countryExample:"örn. Türkiye", birthDate:"Doğum tarihi", optional:"isteğe bağlı", tap:"SAYMAK İÇİN DOKUN", writeCount:"Sayı girin", add:"Ekle", videoProof:"İsteğe bağlı video kanıtı", chooseVideo:"Video seç", save:"Antrenmanı kaydet", saving:"Kaydediliyor …", total:"Toplam", thisMonth:"Bu ay", athletes:"Sporcular", worldwide:"dünya çapında", trainingLog:"Antrenman günlüğünüz", recent:"Son kayıtlarınız.", currentMonth:"Geçerli ay", monthRanking:"Aylık sıralama.", allWorkouts:"Tüm antrenmanlar", totalRanking:"Genel sıralama.", rules:"Kurallar ve dürüstlük", creatorLine:"Topluluk dürüstlüğünüze güvenir.", login:"Giriş / Hesap oluştur", signedIn:"Oturum açıldı", logout:"Çıkış", loading:"Yükleniyor …"};
words.hu = {...words.en, statistics:"Statisztika", worldRecords:"Világrekordok", motivation:"Motiváció", roadTo100:"Út 100 fekvőtámaszig", yourChoice:"Fekvőtámasz-kihívás", lastName:"Vezetéknév", yourLastName:"Vezetékneved", backApp:"Vissza az alkalmazáshoz", communityRanking:"Közösségi ranglista", allAthletes:"Minden sportoló", rankingMotivation:"Nézd meg a közösség eredményeit, és meríts motivációt a következő edzéshez.", rank:"Helyezés", athlete:"Sportoló", monthlyAverage:"Havi átlag", athleteProfile:"Sportolói profil", profileNeeded:"Az első mentés előtt töltsd ki", menRanking:"Nyilvános férfi ranglista", every:"Minden fekvőtámasz számít.", intro:"Add meg a szabályosan végrehajtott fekvőtámaszok számát.", firstName:"A sportoló keresztneve", yourName:"Keresztneved", country:"Ország", countryExample:"pl. Magyarország", birthDate:"Születési dátum", optional:"nem kötelező", profileHelp:"Kötelező: keresztnév és ország. A születési dátum nem kötelező, csak az életkor megjelenítésére szolgál.", tap:"ÉRINTSD MEG A SZÁMLÁLÁSHOZ", writeCount:"Ismétlésszám", add:"Hozzáadás", videoProof:"Opcionális videóbizonyíték", chooseVideo:"Videó kiválasztása", save:"Edzés mentése", saving:"Mentés …", signInHint:"Az edzések mentéséhez és kezeléséhez jelentkezz be e-mail-címmel és jelszóval.", total:"Összesen", thisMonth:"Ebben a hónapban", athletes:"Sportolók", worldwide:"világszerte", trainingLog:"Edzésnaplód", recent:"Legutóbbi bejegyzéseid.", currentMonth:"Aktuális hónap", monthRanking:"Havi ranglista.", allWorkouts:"Minden edzés", totalRanking:"Összesített ranglista.", newcomer:"Igazságos értékelés az újonnan érkezőknek", forecast:"30 napos előrejelzés.", forecastNote:"Az aktív edzésnapok átlaga 30 napra vetítve. Példa: napi 30 ismétlés 900 fekvőtámasz.", rankAthlete:"Helyezés · Sportoló", month:"Hónap", avgDay:"Átlag / nap", activeDays:"Aktív napok", days30:"30 nap", rules:"Szabályok és becsületesség", creatorLine:"A közösség számít a becsületességedre.", login:"Bejelentkezés / Fiók létrehozása", signedIn:"Bejelentkezve mint", logout:"Kijelentkezés", videoFormat:"MP4, WebM vagy MOV · legfeljebb 30 MB", noMonth:"Ebben a hónapban még nincs bejegyzés.", noTotal:"Még nincs bejegyzés az összesített ranglistán.", noForecast:"Az első előrejelzés egy edzés mentése után jelenik meg.", loading:"Betöltés …"};
words.ar = {...words.en, statistics:"الإحصاءات", worldRecords:"الأرقام القياسية العالمية", motivation:"التحفيز", roadTo100:"الطريق إلى 100 تمرين ضغط", yourChoice:"تحدي تمارين الضغط", lastName:"اسم العائلة", yourLastName:"اسم عائلتك", backApp:"العودة إلى التطبيق", communityRanking:"ترتيب المجتمع", allAthletes:"جميع الرياضيين", rank:"الترتيب", athlete:"الرياضي", monthlyAverage:"المتوسط الشهري", athleteProfile:"ملف الرياضي", profileNeeded:"أكمله قبل الحفظ الأول", menRanking:"الترتيب العام للرجال", every:"كل تمرين ضغط مهم.", intro:"اضغط لكل تكرار أو أدخل عدد المجموعة المكتملة.", firstName:"الاسم الأول للرياضي", yourName:"اسمك الأول", country:"الدولة", countryExample:"مثلاً الإمارات", birthDate:"تاريخ الميلاد", optional:"اختياري", tap:"اضغط للعد", writeCount:"أدخل العدد", add:"إضافة", videoProof:"إثبات فيديو اختياري", chooseVideo:"اختر فيديو", save:"حفظ التمرين", saving:"جارٍ الحفظ …", total:"الإجمالي", thisMonth:"هذا الشهر", athletes:"الرياضيون", worldwide:"حول العالم", trainingLog:"سجل تدريباتك", recent:"أحدث إدخالاتك.", currentMonth:"الشهر الحالي", monthRanking:"الترتيب الشهري.", allWorkouts:"كل التدريبات", totalRanking:"الترتيب العام.", rules:"القواعد والنزاهة", creatorLine:"يعتمد المجتمع على النزاهة.", login:"تسجيل الدخول / إنشاء حساب", signedIn:"تم تسجيل الدخول باسم", logout:"تسجيل الخروج", loading:"جارٍ التحميل …"};

export function useLanguage() {
  const [language, setLanguageState] = useState<Language>("de");
  useEffect(() => {
    const saved = localStorage.getItem("pushup-language") as Language | null;
    const browser = navigator.language.slice(0, 2) as Language;
    const next = saved && words[saved] ? saved : words[browser] ? browser : "de";
    setLanguageState(next); document.documentElement.lang = next; document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
  }, []);
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem("pushup-language", next); document.documentElement.lang = next; document.documentElement.dir = next === "ar" ? "rtl" : "ltr"; };
  const t = (key: string, values?: Record<string, string | number>) => {
    let text = extraWords[language][key] || words[language][key] || extraWords.en[key] || words.en[key] || key;
    for (const [name, value] of Object.entries(values || {})) text = text.replaceAll(`{${name}}`, String(value));
    return text;
  };
  return { language, setLanguage, t, locale: ({de:"de-CH",en:"en-GB",fr:"fr-FR",es:"es-ES",it:"it-IT",pt:"pt-PT",bg:"bg-BG",tr:"tr-TR",hu:"hu-HU",ar:"ar"} as Record<Language,string>)[language] };
}
