export const TRAINING_LOG_TEST_CAMPAIGN = {
  id: "training-log-community-test-2026-09-27",
  startsAt: "2026-09-27T07:26:00.000Z",
  endsAt: "2026-09-28T07:26:00.000Z",
  active: true,
  copy: {
    de:{ title:"Teste das Community-Trainingshandbuch", body:"THE.HUMAN.CHOICE ist weiterhin in der Beta-Phase. Du kannst dein Trainingshandbuch für 24 Stunden freiwillig freigeben. Andere Athleten sehen dann deine heutigen Sätze, Wiederholungen und Uhrzeiten, wenn sie in der Statistik auf dein Foto tippen. Du kannst die Freigabe jederzeit im Profil ausschalten.", accept:"Für 24 Stunden freigeben", decline:"Privat lassen" },
    en:{ title:"Try the community training log", body:"THE.HUMAN.CHOICE is still in beta. You can voluntarily share your training log for 24 hours. Other athletes can then see today’s sets, repetitions and times by tapping your photo in the statistics. You can turn sharing off in your profile at any time.", accept:"Share for 24 hours", decline:"Keep private" },
    fr:{ title:"Testez le carnet d’entraînement communautaire", body:"THE.HUMAN.CHOICE est encore en version bêta. Vous pouvez partager volontairement votre carnet pendant 24 heures. Les autres athlètes verront alors vos séries, répétitions et horaires du jour en touchant votre photo dans les statistiques. Vous pouvez désactiver le partage à tout moment dans votre profil.", accept:"Partager pendant 24 heures", decline:"Garder privé" },
    es:{ title:"Prueba el diario de entrenamiento comunitario", body:"THE.HUMAN.CHOICE sigue en fase beta. Puedes compartir voluntariamente tu diario durante 24 horas. Los demás atletas podrán ver tus series, repeticiones y horarios de hoy al tocar tu foto en las estadísticas. Puedes desactivar el acceso en tu perfil en cualquier momento.", accept:"Compartir durante 24 horas", decline:"Mantener privado" },
    it:{ title:"Prova il diario di allenamento della community", body:"THE.HUMAN.CHOICE è ancora in beta. Puoi condividere volontariamente il tuo diario per 24 ore. Gli altri atleti vedranno le serie, le ripetizioni e gli orari di oggi toccando la tua foto nelle statistiche. Puoi disattivare la condivisione dal profilo in qualsiasi momento.", accept:"Condividi per 24 ore", decline:"Mantieni privato" },
    pt:{ title:"Experimente o diário de treino da comunidade", body:"THE.HUMAN.CHOICE continua em versão beta. Pode partilhar voluntariamente o seu diário durante 24 horas. Os outros atletas poderão ver as séries, repetições e horários de hoje ao tocar na sua fotografia nas estatísticas. Pode desativar a partilha no perfil a qualquer momento.", accept:"Partilhar durante 24 horas", decline:"Manter privado" },
    bg:{ title:"Изпробвайте общностния тренировъчен дневник", body:"THE.HUMAN.CHOICE все още е в бета версия. Можете доброволно да споделите тренировъчния си дневник за 24 часа. Другите спортисти ще виждат днешните серии, повторения и часове, когато докоснат снимката ви в статистиката. Можете да изключите споделянето от профила си по всяко време.", accept:"Споделяне за 24 часа", decline:"Остави лично" },
    tr:{ title:"Topluluk antrenman günlüğünü dene", body:"THE.HUMAN.CHOICE hâlâ beta aşamasındadır. Antrenman günlüğünü gönüllü olarak 24 saat paylaşabilirsin. Diğer sporcular istatistiklerde fotoğrafına dokunarak bugünkü setlerini, tekrarlarını ve saatlerini görebilir. Paylaşımı profilinden istediğin zaman kapatabilirsin.", accept:"24 saat paylaş", decline:"Gizli tut" },
    hu:{ title:"Próbáld ki a közösségi edzésnaplót", body:"A THE.HUMAN.CHOICE még béta verzióban működik. Edzésnaplódat önkéntesen 24 órára megoszthatod. A többi sportoló a statisztikában a fotódra koppintva láthatja a mai sorozataidat, ismétléseidet és azok időpontját. A megosztást a profilodban bármikor kikapcsolhatod.", accept:"Megosztás 24 órára", decline:"Maradjon privát" },
    ar:{ title:"جرّب سجل التدريب المجتمعي", body:"لا يزال THE.HUMAN.CHOICE في المرحلة التجريبية. يمكنك مشاركة سجل تدريبك طوعًا لمدة 24 ساعة. سيتمكن الرياضيون الآخرون من رؤية مجموعات اليوم وعدد التكرارات وأوقاتها عند الضغط على صورتك في الإحصاءات. يمكنك إيقاف المشاركة من ملفك الشخصي في أي وقت.", accept:"المشاركة لمدة 24 ساعة", decline:"إبقاؤه خاصًا" },
  },
} as const;
