import { LegalLayout } from "../legal-layout";

export default function PrivacyPage() {
  return <LegalLayout title="Datenschutzerklärung">
    <section><h2>1. Verantwortlicher</h2><address><strong>Roman Dossenbach</strong><br />Steinackerstrasse 16<br />79576 Weil am Rhein<br />Deutschland</address><p>E-Mail: <a href="mailto:pushupmania@gmail.com">pushupmania@gmail.com</a></p></section>
    <section><h2>2. Geltungsbereich</h2><p>Diese Datenschutzerklärung gilt für THE.HUMAN.CHOICE und Road to 100 Push-ups. Beide Apps verwenden ein gemeinsames Benutzerkonto und Athletenprofil. Trainingsergebnisse werden automatisch zwischen den Apps synchronisiert.</p></section>
    <section><h2>3. Verarbeitete Daten</h2><p>Je nach Nutzung werden Name oder Anzeigename, abgekürzter Nachname, E-Mail-Adresse, verschlüsselte Authentifizierungsdaten, Alter oder Geburtsdaten, Geschlecht, Land, freiwilliges Profilfoto, Trainingseinträge, Zeitpunkte, Tages-, Monats-, Gesamt- und Durchschnittswerte, Rangpositionen, Einstellungen, Einwilligungen, Supportnachrichten sowie technisch erforderliche Geräte-, Browser-, IP- und Protokolldaten verarbeitet.</p></section>
    <section><h2>4. Zwecke und Rechtsgrundlagen</h2><p>Kontoführung, Anmeldung, Speicherung, Statistiken und Synchronisierung erfolgen zur Vertragserfüllung nach Art. 6 Abs. 1 Buchstabe b DSGVO. Die Veröffentlichung freiwilliger Profilangaben und eines Profilfotos beruht auf einer Einwilligung nach Art. 6 Abs. 1 Buchstabe a DSGVO. Sicherheits- und Fehlerprotokolle werden aufgrund des berechtigten Interesses an einem sicheren Betrieb nach Art. 6 Abs. 1 Buchstabe f DSGVO verarbeitet. Gesetzliche Pflichten beruhen auf Art. 6 Abs. 1 Buchstabe c DSGVO.</p></section>
    <section><h2>5. Gemeinsames Konto und Synchronisierung</h2><p>Bei Verwendung derselben E-Mail-Adresse werden die Anmeldedaten einem gemeinsamen Konto zugeordnet. In einer App erfasste Liegestütze und Trainingsergebnisse werden ohne zusätzliche Einzelbestätigung in die andere App übernommen. Dadurch werden doppelte Profile und voneinander abweichende Statistiken vermieden.</p></section>
    <section><h2>6. Öffentliche Rangliste</h2><p>Mit Einwilligung können Vorname, abgekürzter Nachname, Alter oder Altersklasse, Land, Geschlecht beziehungsweise Kategorie, freiwilliges Profilfoto, Trainingsleistungen, Durchschnitt und Rangposition veröffentlicht werden. E-Mail-Adresse, Passwort, Anschrift und vollständiges Geburtsdatum werden nicht veröffentlicht. Die Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden.</p></section>
    <section><h2>7. Supabase</h2><p>Für Registrierung, Anmeldung, Datenbank, Speicherung und Synchronisierung wird Supabase eingesetzt:</p><address><strong>Supabase Pte. Ltd.</strong><br />65 Chulia Street #38-02/03<br />OCBC Centre<br />Singapore 049513<br />E-Mail: privacy@supabase.io</address><p>Die primären Projektdaten werden in der Serverregion <strong>Central EU (Frankfurt), Deutschland</strong> gespeichert. Supabase verarbeitet Kontodaten, Authentifizierungsdaten, Profildaten, Trainingseinträge, IP-Adressen sowie erforderliche Sicherheitsprotokolle als Auftragsverarbeiter. Soweit eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums stattfindet, stützt sie sich insbesondere auf EU-Standardvertragsklauseln gemäß Art. 46 DSGVO.</p><p><a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">Datenschutzhinweise von Supabase</a></p></section>
    <section><h2>8. Technisch notwendige Speicherung</h2><p>Die Apps verwenden ausschließlich technisch notwendige Cookies oder vergleichbare Speichertechniken für Anmeldung, sichere Sitzungen, Spracheinstellungen und grundlegende Funktionen. Es werden keine Werbe-, Zahlungs-, Marketing- oder eigenen Analysedienste eingesetzt. Es bestehen keine Social-Media-Plugins und keine Anmeldung über soziale Netzwerke. Reine externe Links zu Social-Media-Seiten übertragen erst beim Anklicken Daten an den jeweiligen Anbieter.</p></section>
    <section><h2>9. Empfänger und Speicherdauer</h2><p>Daten werden nur an erforderliche Hosting-, Datenbank- und Authentifizierungsdienstleister sowie bei gesetzlicher Verpflichtung an Behörden oder Gerichte übermittelt. Freigegebene Ranglistendaten sind für andere Nutzer sichtbar. Daten werden gespeichert, solange das Konto besteht oder sie für den Betrieb benötigt werden. Nach der Kontolöschung werden sie gelöscht oder anonymisiert, soweit keine gesetzlichen Aufbewahrungspflichten oder begrenzten Sicherheitsgründe entgegenstehen.</p></section>
    <section><h2>10. Kontolöschung</h2><p>Das gemeinsame Konto kann in den persönlichen Daten über „Konto löschen“ oder per E-Mail an pushupmania@gmail.com gelöscht werden. Die Löschung gilt für beide Apps und entfernt die zugeordneten Profile und Trainingseinträge, soweit keine gesetzliche Pflicht zur weiteren Speicherung besteht.</p></section>
    <section><h2>11. Rechte</h2><p>Betroffene Personen haben nach den gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie das Recht, Einwilligungen mit Wirkung für die Zukunft zu widerrufen. Anfragen können an pushupmania@gmail.com gerichtet werden.</p></section>
    <section><h2>12. Beschwerderecht</h2><p>Beschwerden können an den Landesbeauftragten für den Datenschutz und die Informationsfreiheit Baden-Württemberg, Lautenschlagerstraße 20, 70173 Stuttgart, gerichtet werden: <a href="https://www.baden-wuerttemberg.datenschutz.de" target="_blank" rel="noreferrer">baden-wuerttemberg.datenschutz.de</a>.</p></section>
    <section><h2>13. Minderjährige und Sicherheit</h2><p>Die selbstständige Nutzung ist grundsätzlich ab 16 Jahren vorgesehen. Für jüngere Nutzer ist, soweit erforderlich, die Zustimmung der Erziehungsberechtigten einzuholen. Angemessene technische und organisatorische Maßnahmen schützen die Daten vor Verlust, Veränderung und unbefugtem Zugriff.</p></section>
    <section><h2>14. Änderungen</h2><p>Diese Datenschutzerklärung wird angepasst, wenn sich Funktionen, Dienstleister oder gesetzliche Anforderungen ändern. Die aktuelle Fassung wird in beiden Apps veröffentlicht.</p></section>
  </LegalLayout>;
}
